/*
ScalaFromJS: 2017-12-05 14:38:17.341
syntax.js
*/

package esprima

object Syntax {
  var AssignmentExpression = "AssignmentExpression"
  var AssignmentPattern = "AssignmentPattern"
  var ArrayExpression = "ArrayExpression"
  var ArrayPattern = "ArrayPattern"
  var ArrowFunctionExpression = "ArrowFunctionExpression"
  var AwaitExpression = "AwaitExpression"
  var BlockStatement = "BlockStatement"
  var BinaryExpression = "BinaryExpression"
  var BreakStatement = "BreakStatement"
  var CallExpression = "CallExpression"
  var CatchClause = "CatchClause"
  var ClassBody = "ClassBody"
  var ClassDeclaration = "ClassDeclaration"
  var ClassExpression = "ClassExpression"
  var ConditionalExpression = "ConditionalExpression"
  var ContinueStatement = "ContinueStatement"
  var DoWhileStatement = "DoWhileStatement"
  var DebuggerStatement = "DebuggerStatement"
  var EmptyStatement = "EmptyStatement"
  var ExportAllDeclaration = "ExportAllDeclaration"
  var ExportDefaultDeclaration = "ExportDefaultDeclaration"
  var ExportNamedDeclaration = "ExportNamedDeclaration"
  var ExportSpecifier = "ExportSpecifier"
  var ExpressionStatement = "ExpressionStatement"
  var ForStatement = "ForStatement"
  var ForOfStatement = "ForOfStatement"
  var ForInStatement = "ForInStatement"
  var FunctionDeclaration = "FunctionDeclaration"
  var FunctionExpression = "FunctionExpression"
  var Identifier = "Identifier"
  var IfStatement = "IfStatement"
  var Import = "Import"
  var ImportDeclaration = "ImportDeclaration"
  var ImportDefaultSpecifier = "ImportDefaultSpecifier"
  var ImportNamespaceSpecifier = "ImportNamespaceSpecifier"
  var ImportSpecifier = "ImportSpecifier"
  var Literal = "Literal"
  var LabeledStatement = "LabeledStatement"
  var LogicalExpression = "LogicalExpression"
  var MemberExpression = "MemberExpression"
  var MetaProperty = "MetaProperty"
  var MethodDefinition = "MethodDefinition"
  var NewExpression = "NewExpression"
  var ObjectExpression = "ObjectExpression"
  var ObjectPattern = "ObjectPattern"
  var Program = "Program"
  var Property = "Property"
  var RestElement = "RestElement"
  var ReturnStatement = "ReturnStatement"
  var SequenceExpression = "SequenceExpression"
  var SpreadElement = "SpreadElement"
  var Super = "Super"
  var SwitchCase = "SwitchCase"
  var SwitchStatement = "SwitchStatement"
  var TaggedTemplateExpression = "TaggedTemplateExpression"
  var TemplateElement = "TemplateElement"
  var TemplateLiteral = "TemplateLiteral"
  var ThisExpression = "ThisExpression"
  var ThrowStatement = "ThrowStatement"
  var TryStatement = "TryStatement"
  var UnaryExpression = "UnaryExpression"
  var UpdateExpression = "UpdateExpression"
  var VariableDeclaration = "VariableDeclaration"
  var VariableDeclarator = "VariableDeclarator"
  var WhileStatement = "WhileStatement"
  var WithStatement = "WithStatement"
  var YieldExpression = "YieldExpression"
}
