name: Deploy

on:
  push:
    tags:
      - v*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Publish
      run: |
        printf "[github]\n  actor=${{ secrets.GITHUB_USERNAME }}\n  token=${{ secrets.GITHUB_USERTOKEN }}" > ~/.gitconfig
        sbt +projsJVM/publish +projsJS/publish
